name = "4x8matrix/cli_builder"
version = "0.1.0-dev.1"
description = "A CLI Builder for Luau"
license = "MIT"
authors = ["Async Matrix <hi@asyncmatrix.dev>"]
private = false
includes = ["src/**/*", "pesde.toml", "LICENSE", "readme.md"]

[target]
environment = "luau"
lib = "src/init.luau"

[dev_dependencies.frktest]
name = "itsfrank/frktest"
version = "^0.0.2"
index = "https://github.com/pesde-pkg/index"
target = "lune"
